### ISSUE TITLE
[context] Do we *need* `multiple` and `dispose()`?

### ISSUE THREAD

**Issue by dgp1130** [webcomponents-cg/community-protocols#37]
The current context proposal suggests that context requests can include `multiple` to request that the callback be invoked multiple times as the value changes, and use a `dispose` value to communicate that it would like to unsubscribe from the context. This seems like very nuanced semantics for APIs which already exist. Promises, arrays, generators, `EventTarget`, subscribables, signals, etc. all provide different forms of "update this value over time" with varying semantics between the provider and receiver. As a rough approximation of some of these semantics:

* `Promise` - Resolves or rejects at some unspecified time in the future at most once.
* `Array` - Provides many values at exactly one time.
* `Generator` - Provides many values in a pull-based model.
* `EventTarget` - Provides many values in a push-based model with explicit unsubscription.
* `Subscribables` - Provides many values in an asynchronous push or pull-based model with explicit unsubscription.
* Signals - Provides many values in a synchronous pull-based model with implicit unsubscription (I think, I'm not very familiar with signals).

I propose an alternative: Remove `dispose` and `multiple`. Instead, do nothing. Let the provided value itself be wrapped in the appropriate container with which to define the usage contract. A single value might be `Context<number>`, while a value updated over time would be `Context<Subscribable<number>>`.

This approach provides all the same flexibility without any additional implementation complexity.

The one trade-off here which I see is that it requires the provider / context definition to choose the reactivity model of the context value and the context requester just has to make that work. It also means all context receivers need to use the same model (or else subscribe to different contexts from the same provider, which is awkward but workable).

I can see an argument that the provider should always provide updates over time and it's up to requesters to decide if and how much of those updates they want to accept. However, I don't think argument completely holds because requestors specifically tell the provider whether they expect updates over time via `multiple`, and the very nature of `dispose()` acts as an "unsubscribe" which implies the provider can stop publishing updates to a context if no one is subscribed to it. Both of these indicate that the behavior of the provider is dependent on the options defined by the requestors and their runtime behavior anyways. As a result, I don't think we can look at providers through the lens of "always provide all the context and let requestors deal with it how they choose".

I think it would be better to just let providers choose the reactivity model they are willing to support and letting context requestors work with that API. What do others think about this? Am I misunderstanding the purpose of `multiple` and `dispose()`?

**Comment by Westbrook** [comment]
With `multiple` and `dispose` both being optional arguments, I think the protocol itself answers this question, no we don't _need_ them.

*Without them*, a Provider is free to deliver any of the more complex values that you've defined here. Though it does become the responsibility of the Provider to document those complexities and then Consumer to actively manage those complexities.

*With them*, even simple data types can be kept up-to-date without the intervention of a second management context. This means that if you choose to use `multiple` and `dispose` then the value can always be assumed to be update over time without knowing anything about how to leverage that data.

This flexibility feels like a good balance of capability and API options without being overly strict. In that way, there are even more reactivity models that a Provider can support and they are still able to choose which one they are willing to support.

**Comment by dgp1130** [comment]
> With multiple and dispose both being optional arguments, I think the protocol itself answers this question, no we don't need them.

> Though it does become the responsibility of the Provider to document those complexities and then Consumer to actively manage those complexities.

I think these are the key points and which directly conflict with each other. `dispose()` is _not_ optional in the current proposal because any consumer needs to defensively support it _just in case_ the provider requires it.

Of course in an application with two cooperating components maintained in the same codebase with the sbar and ownership, devs can short-cut this process knowing that no, the provider really doesn't require `dispose()`. But especially in the context of a community protocol, the loose coupling between provider and consumer means that they can't make any assumptions about each other, including whether or not the value should be disposed.

Here's a related question to frame the conversation: Consider a library with a provider component shipped to users and working successfully. This provider does *not* send a `dispose()` function because it just isn't necessary. Then one day, I make a change which now requires cleanup, so I add a `dispose()` function and release a new version. Is this change:
1. A breaking change because consumers were not expected to implement `dispose()` previously and now they are.
2. A non-breaking change because consumers _were_ expected to defensively implement a previously unused `dispose()`, and since they didn't they have a bad consumer which broke the protocol.

As the protocol is currently written I feel like 2. is at least somewhat implied, but in practice in such a situation I'd probably go with 1. just to avoid angering users. Of course as a provider, I'd probably just not use `dispose()` and instead use my own reactivity primitive specifically to avoid this. But the question still remains for consumers which don't have luxury.

Every situation is different and we don't necessarily need to decide on a "correct" answer on breaking changed here, but I think it demonstrates the "need" for `dispose()` as the protocol is currently written and why there might be value in removing it.

**Comment by justinfagnani** [comment]
The reason why `multiple` and `dispose()` are needed is to reduce memory overhead when a provider can deliver new values. If the consumer is never going to use updated values, then the provider doesn't need to keep a reference to the context-request event's callback. So providers should only store the callback if `multiple` is true. Then if the consumer no longer needs the values, like when it's disconnected, it should call `dispose()` to tell the provider to release the reference to the callback.

Doing this releasing easily and ergonomically is critical because if a provider holds on to a callback when it shouldn't, and that callback closure has references into the consumer element (almost all will), then the provider will hold on to consumer elements, which could be a serious memory leak. The nice thing about this subscribe/dispose protocol is that it's very easily abstracted into helpers that do the right thing on host element disconnection to avoid those leaks. The `@lit-labs/context` package automatically hooks `disconnectedCallback()` to call `dispose()`. I think that kind of DX is very important to ensure correct usage.

The problem with other "subscription" techniques:
- Promises are async only and one-shot only.
- Arrays don't notify of new values
- Generators require a lot of ceremony to get the same behavior, and probably in fact need the same `multiple`/`dispose()` API. A provider can't have a single generator per value, because only one consumer would get each value. So it needs to maintain a generator per consumer. But then it needs to know when to release that generator, so it needs a `dispose()` mechanism.
- EventTargets are ok, but this protocol already uses Events a lot, and they're ore heavyweight than function calls, and we need to watch out for performance here. You also would need to call `removeEventLister()` very similarly to `dispose()`.
- Subscribables - I don't know what these are. I don't think there's anything by that name in JS or DOM?
- Signals - same.

**Comment by dgp1130** [comment]
> The problem with other "subscription" techniques:

I'm not advocating for any of these as a coon dispose mechanism. Only using them to illustrate the options snd trade offs a provider can choose to use. The protocol itself wouldn't specify any of these, just like it doesn't today.

> Subscribables - I don't know what these are. I don't think there's anything by that name in JS or DOM?

I was referring to the interface for consuming `Obervables` without an RxJS dependency.

https://rxjs.dev/api/index/interface/Subscribable

> Signals - same.

https://www.solidjs.com/tutorial/introduction_signals

Again, not saying the protocol should use any of these, just that providers can choose what works for them.

> The nice thing about this subscribe/dispose protocol is that it's very easily abstracted into helpers that do the right thing on host element disconnection to avoid those leaks. The `@lit-labs/context` package automatically hooks `disconnectedCallback()` to call `dispose()`. I think that kind of DX is very important to ensure correct usage.

That is a good point. I can see how a standard dispose semantic would be useful for component libraries to implement implicitly so devs don't have to think about it as much. If the dispose semantics are unique to each context and the exact reactivity primitive it choose, then the component library can't do much to abstract away that complexity.

I think for that reason alone I'm convinced that we should have a common dispose mechanism. Apologies for any noise here, it's just helpful to explicitly call out motivations like this sometimes.

Sidebar: Lit's implementation is eerily similar to [one I was working on](https://github.com/dgp1130/Hydrator/blob/9028026ea0016dba9e862a0d3a25edb98c5afc6e/src/examples/context-counter.ts) which motivated this issue. 😅

**Comment by benjamind** [comment]
All good points raised, and honestly I went back and forth a number of times on the value of these arguments. In the end it just came down to keeping the protocol as flexible as possible without putting undue burden on implementors. Glad this made sense to more folks than just me!
